### ISSUE TITLE
Coveralls Badge unknown

### ISSUE THREAD

**Issue by JPeer264** [gulpjs/bach#25]
On [bach's coveralls](https://coveralls.io/github/gulpjs/bach), there is no `master` branch - so the badge will link to an unknown branch. You may have to sync the branches in coveralls to get a correct badge again.

**Comment by phated** [comment]
I'd rather figure out why there is no master branch so I don't have to update this when changes are made.  Can you look into that?

**Comment by JPeer264** [comment]
Hm pretty weird. Master branch is back in coveralls but the coverage is still missing. The only thing I can think of is that it should get triggered one more time by travis. I also never had this before, and after some research I couldn't find another solution.

**Comment by phated** [comment]
@JPeer264 I'm actually going to stop pointing at master for the badge, like I did in `glob-stream`. It's not the perfect solution but we don't point at master for travis/appveyor either.

**Comment by phated** [comment]
Closed by #27
